### ISSUE TITLE
Parameters are stringified twice

### ISSUE THREAD

**Issue by andryyy** [Emtyloc/json-enc-custom#1]
Hi,

Thanks for the useful modification of the json-enc. 👍🏻 

https://github.com/Emtyloc/json-enc-custom/blob/f3fbbe540d5a280f1302177f590469bfe1f83f5e/json-enc-custom.js#L10

On line 10 the returned data is stringified a second time, resulting in a string of escaped JSON data.

I removed it for me to receive an unescaped JSON object on the server.

André

**Comment by Emtyloc** [comment]
oh thanks, I didn't notice, I will fix it as soon as possible.

**Comment by andryyy** [comment]
Oh, cool, thank you!
