### ISSUE TITLE
Checkbox without value is not converted to boolean

### ISSUE THREAD

**Issue by LaybeRize** [Emtyloc/json-enc-custom#2]
The example states that
```
...
<input type='checkbox' name='shiny' checked>
// produces
{
  ...
  "shiny":  true
}
```
but when I tried to replicate that, it returned
```
{
  ...
  "shiny":  "on"
}
```
instead.

**Comment by LaybeRize** [comment]
Fixed this via adding an if statement into the encodingAlgorithm Function:

```js
function encodingAlgorithm(parameters) {
    let resultingObject = Object.create(null);
    const PARAM_NAMES = Object.keys(parameters);
    const PARAM_VALUES = Object.values(parameters);
    const PARAM_LENGHT = PARAM_NAMES.length;

    for (let param_index = 0; param_index < PARAM_LENGHT; param_index++) {
        let name = PARAM_NAMES[param_index];
        let value = PARAM_VALUES[param_index];
       // this if statement is new
        if (document.querySelectorAll("input[type=checkbox][name='"+name+"']").length === 1 &&
            document.querySelectorAll("input[type=checkbox][name='"+name+"']").item(0).attributes.getNamedItem("value") === null) {
            value = value === "on";
        }
        let steps = JSONEncodingPath(name);
        let context = resultingObject;

        for (let step_index = 0; step_index < steps.length; step_index++) {
            let step = steps[step_index];
            context = setValueFromPath(context, step, value);
        }
    }

    let result = JSON.stringify(resultingObject);
    return result
}
```

**Comment by Emtyloc** [comment]
For the time being, I will update the readme. However, I'm trying to figure out an idea of how to implement this without breaking web standards or browser compatibility. I will update the extension as soon as I get a clear idea of how to handle the boolean values from the checkboxes and possibly other input fields.
thanks for your time.

**Comment by Emtyloc** [comment]
To avoid conflicts and after researching the standards for checkboxes, it is better to keep "on" as the default value. This way, the extension is less intrusive in terms of the browser's behavior. Anyway, thank you for your time, and I hope the extension continues to be useful for you.

**Comment by LaybeRize** [comment]
Understandable. On that note I also discovered, that the documentation mentions a number array, but the script itself doesn't convert anything from the string value into any other type.

**Comment by Emtyloc** [comment]
You are right, that is something that needs to be fixed. Thanks for your feedback!
